name: feature_reports
description: Sales reports and analytics feature
publish_to: none
resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.5'

dependencies:
  auto_route: ^11.1.0
  bloc_exports:
    path: ../../packages/bloc
  catalog:
    path: ../../packages/catalog
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  i18n:
    path: ../../packages/i18n
  logger:
    path: ../../packages/logger
  order_management:
    path: ../../packages/order_management
  result:
    path: ../../packages/result
  talker: ^5.1.9
  ui_kit:
    path: ../../packages/ui_kit
  utils:
    path: ../../packages/utils

dev_dependencies:
  auto_route_generator: ^10.2.6
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
