// Mocks generated by Mockito 5.4.6 from annotations
// in agora/test/products/blocs/products/products_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:agora/core/misc/result.dart' as _i5;
import 'package:agora/products/models/category/category.dart' as _i8;
import 'package:agora/products/models/product/product.dart' as _i4;
import 'package:agora/products/repositories/categories_repository.dart' as _i7;
import 'package:agora/products/repositories/products_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProductsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRepository extends _i1.Mock
    implements _i2.ProductsRepository {
  MockProductsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Product>> watchAllProducts() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllProducts, []),
            returnValue: _i3.Stream<List<_i4.Product>>.empty(),
          )
          as _i3.Stream<List<_i4.Product>>);

  @override
  _i3.Stream<List<_i4.Product>> watchProductsByCategory(int? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#watchProductsByCategory, [categoryId]),
            returnValue: _i3.Stream<List<_i4.Product>>.empty(),
          )
          as _i3.Stream<List<_i4.Product>>);

  @override
  _i3.Stream<_i4.Product?> watchProductById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchProductById, [id]),
            returnValue: _i3.Stream<_i4.Product?>.empty(),
          )
          as _i3.Stream<_i4.Product?>);

  @override
  _i3.Future<_i5.Result<_i4.Product?>> getProductById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i3.Future<_i5.Result<_i4.Product?>>.value(
              _i6.dummyValue<_i5.Result<_i4.Product?>>(
                this,
                Invocation.method(#getProductById, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.Product?>>);

  @override
  _i3.Future<_i5.Result<_i4.Product?>> getProductBySku(String? sku) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBySku, [sku]),
            returnValue: _i3.Future<_i5.Result<_i4.Product?>>.value(
              _i6.dummyValue<_i5.Result<_i4.Product?>>(
                this,
                Invocation.method(#getProductBySku, [sku]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.Product?>>);

  @override
  _i3.Future<_i5.Result<int>> getProductsCount({
    int? categoryId,
    String? searchTerm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsCount, [], {
              #categoryId: categoryId,
              #searchTerm: searchTerm,
            }),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i6.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#getProductsCount, [], {
                  #categoryId: categoryId,
                  #searchTerm: searchTerm,
                }),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);

  @override
  _i3.Future<_i5.Result<_i4.Product>> createProduct(_i4.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#createProduct, [product]),
            returnValue: _i3.Future<_i5.Result<_i4.Product>>.value(
              _i6.dummyValue<_i5.Result<_i4.Product>>(
                this,
                Invocation.method(#createProduct, [product]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.Product>>);

  @override
  _i3.Future<_i5.Result<_i4.Product>> updateProduct(_i4.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i3.Future<_i5.Result<_i4.Product>>.value(
              _i6.dummyValue<_i5.Result<_i4.Product>>(
                this,
                Invocation.method(#updateProduct, [product]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.Product>>);

  @override
  _i3.Future<_i5.Result<int>> deleteProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i6.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#deleteProduct, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);

  @override
  _i3.Future<_i5.Result<bool>> restoreProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#restoreProduct, [id]),
            returnValue: _i3.Future<_i5.Result<bool>>.value(
              _i6.dummyValue<_i5.Result<bool>>(
                this,
                Invocation.method(#restoreProduct, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<bool>>);
}

/// A class which mocks [CategoriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoriesRepository extends _i1.Mock
    implements _i7.CategoriesRepository {
  MockCategoriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i8.Category>> watchAllCategories() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllCategories, []),
            returnValue: _i3.Stream<List<_i8.Category>>.empty(),
          )
          as _i3.Stream<List<_i8.Category>>);

  @override
  _i3.Stream<_i8.Category?> watchCategoryById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchCategoryById, [id]),
            returnValue: _i3.Stream<_i8.Category?>.empty(),
          )
          as _i3.Stream<_i8.Category?>);

  @override
  _i3.Future<_i5.Result<_i8.Category?>> getCategoryById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryById, [id]),
            returnValue: _i3.Future<_i5.Result<_i8.Category?>>.value(
              _i6.dummyValue<_i5.Result<_i8.Category?>>(
                this,
                Invocation.method(#getCategoryById, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i8.Category?>>);

  @override
  _i3.Future<_i5.Result<int>> getCategoriesCount() =>
      (super.noSuchMethod(
            Invocation.method(#getCategoriesCount, []),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i6.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#getCategoriesCount, []),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);

  @override
  _i3.Future<_i5.Result<_i8.Category>> createCategory(_i8.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#createCategory, [category]),
            returnValue: _i3.Future<_i5.Result<_i8.Category>>.value(
              _i6.dummyValue<_i5.Result<_i8.Category>>(
                this,
                Invocation.method(#createCategory, [category]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i8.Category>>);

  @override
  _i3.Future<_i5.Result<_i8.Category>> updateCategory(_i8.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#updateCategory, [category]),
            returnValue: _i3.Future<_i5.Result<_i8.Category>>.value(
              _i6.dummyValue<_i5.Result<_i8.Category>>(
                this,
                Invocation.method(#updateCategory, [category]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i8.Category>>);

  @override
  _i3.Future<_i5.Result<int>> deleteCategory(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategory, [id]),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i6.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#deleteCategory, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);

  @override
  _i3.Future<_i5.Result<bool>> restoreCategory(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#restoreCategory, [id]),
            returnValue: _i3.Future<_i5.Result<bool>>.value(
              _i6.dummyValue<_i5.Result<bool>>(
                this,
                Invocation.method(#restoreCategory, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<bool>>);
}
