name: agora_workspace
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.38.5'

workspace:
  - apps/agora
  - features/auth
  - features/discounts
  - features/inventory
  - features/orders
  - features/pos
  - features/products
  - features/reports
  - features/settings
  - packages/app_info
  - packages/bloc
  - packages/database
  - packages/errors
  - packages/i18n
  - packages/launcher
  - packages/logger
  - packages/observer
  - packages/remote_config
  - packages/result
  - packages/sync_engine
  - packages/theme
  - packages/ui_kit
  - packages/utils

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^7.4.0
  # Linting
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  # Code generation
  build_runner: ^2.4.7
  build: ^3.0.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  auto_route_generator: ^10.2.6
  drift_dev: ^2.30.0
  slang_build_runner: ^4.10.0
  flutter_gen_runner:
  # Testing
  bloc_test: ^10.0.0
  mockito: ^5.5.0
  data_fixture_dart: ^3.0.0
  test: ^1.24.0
