// Mocks generated by Mockito 5.4.6 from annotations
// in sync_engine/test/sync_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:sync_engine/src/connectivity/connectivity_monitor.dart' as _i5;
import 'package:sync_engine/src/model/outbox_entry.dart' as _i4;
import 'package:sync_engine/src/outbox/outbox_queue.dart' as _i2;
import 'package:sync_engine/src/sync_handler.dart' as _i8;
import 'package:sync_engine/src/websocket/sync_message.dart' as _i7;
import 'package:sync_engine/src/websocket/sync_web_socket.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OutboxQueue].
///
/// See the documentation for Mockito's code generation for more information.
class MockOutboxQueue extends _i1.Mock implements _i2.OutboxQueue {
  MockOutboxQueue() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<int> get pendingCount =>
      (super.noSuchMethod(
            Invocation.getter(#pendingCount),
            returnValue: _i3.Stream<int>.empty(),
          )
          as _i3.Stream<int>);

  @override
  _i3.Future<void> enqueue({
    required String? entityType,
    required _i4.OutboxOperation? operation,
    required String? entityLocalId,
    required Map<String, dynamic>? payload,
    String? remoteId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enqueue, [], {
              #entityType: entityType,
              #operation: operation,
              #entityLocalId: entityLocalId,
              #payload: payload,
              #remoteId: remoteId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.OutboxEntry>> pendingEntries() =>
      (super.noSuchMethod(
            Invocation.method(#pendingEntries, []),
            returnValue: _i3.Future<List<_i4.OutboxEntry>>.value(
              <_i4.OutboxEntry>[],
            ),
          )
          as _i3.Future<List<_i4.OutboxEntry>>);

  @override
  _i3.Future<void> markInflight(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#markInflight, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markDone(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#markDone, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markFailed(
    int? id,
    String? reason,
    int? currentRetryCount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markFailed, [id, reason, currentRetryCount]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> purgeFailed() =>
      (super.noSuchMethod(
            Invocation.method(#purgeFailed, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ConnectivityMonitor].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityMonitor extends _i1.Mock
    implements _i5.ConnectivityMonitor {
  MockConnectivityMonitor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<bool> get isOnline =>
      (super.noSuchMethod(
            Invocation.getter(#isOnline),
            returnValue: _i3.Stream<bool>.empty(),
          )
          as _i3.Stream<bool>);

  @override
  _i3.Future<bool> get currentStatus =>
      (super.noSuchMethod(
            Invocation.getter(#currentStatus),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [SyncWebSocket].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncWebSocket extends _i1.Mock implements _i6.SyncWebSocket {
  MockSyncWebSocket() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i7.WebSocketConnectionStatus> get connectionStatus =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStatus),
            returnValue: _i3.Stream<_i7.WebSocketConnectionStatus>.empty(),
          )
          as _i3.Stream<_i7.WebSocketConnectionStatus>);

  @override
  _i3.Stream<_i7.SyncMessage> get messages =>
      (super.noSuchMethod(
            Invocation.getter(#messages),
            returnValue: _i3.Stream<_i7.SyncMessage>.empty(),
          )
          as _i3.Stream<_i7.SyncMessage>);

  @override
  _i3.Future<void> connect(String? url, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [url, token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void subscribe(String? topic) => super.noSuchMethod(
    Invocation.method(#subscribe, [topic]),
    returnValueForMissingStub: null,
  );

  @override
  void unsubscribe(String? topic) => super.noSuchMethod(
    Invocation.method(#unsubscribe, [topic]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SyncHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncHandler extends _i1.Mock implements _i8.SyncHandler {
  MockSyncHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get entityType =>
      (super.noSuchMethod(
            Invocation.getter(#entityType),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#entityType),
            ),
          )
          as String);

  @override
  _i3.Future<void> handle(_i4.OutboxEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#handle, [entry]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
