// Mocks generated by Mockito 5.4.6 from annotations
// in feature_products/test/repositories/products_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:database/database.dart' as _i2;
import 'package:drift/drift.dart' as _i3;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:feature_products/data/sources/local/daos/modifiers_dao.dart'
    as _i10;
import 'package:feature_products/data/sources/local/daos/products_dao.dart'
    as _i6;
import 'package:inventory_contracts/repositories/inventory_repository.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:result/result.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAgoraDatabase_0 extends _i1.SmartFake implements _i2.AgoraDatabase {
  _FakeAgoraDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_1 extends _i1.SmartFake
    implements _i3.DatabaseConnection {
  _FakeDatabaseConnection_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_2 extends _i1.SmartFake
    implements _i3.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_3 extends _i1.SmartFake implements _i3.QueryExecutor {
  _FakeQueryExecutor_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_4 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_5 extends _i1.SmartFake
    implements _i3.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_6<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_7<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.InsertStatement<T1, D1> {
  _FakeInsertStatement_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_8<T extends _i3.Table, D> extends _i1.SmartFake
    implements _i3.UpdateStatement<T, D> {
  _FakeUpdateStatement_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_9<T1 extends _i3.HasResultSet, D>
    extends _i1.SmartFake
    implements _i3.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_10<FirstT extends _i3.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i3.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_11<Row> extends _i1.SmartFake
    implements _i3.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_12<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_13<T> extends _i1.SmartFake implements _i3.Selectable<T> {
  _FakeSelectable_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_14 extends _i1.SmartFake
    implements _i3.GenerationContext {
  _FakeGenerationContext_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductsDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsDao extends _i1.Mock implements _i6.ProductsDao {
  MockProductsDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AgoraDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeAgoraDatabase_0(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i2.AgoraDatabase);

  @override
  _i3.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_1(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i3.DatabaseConnection);

  @override
  _i3.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_2(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i3.DriftDatabaseOptions);

  @override
  _i3.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i7.dummyValue<_i3.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i3.SqlTypes);

  @override
  _i3.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_3(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i3.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_4(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i4.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_5(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i3.DatabaseConnectionUser);

  @override
  _i5.Stream<List<_i2.ProductEntity>> watchAllProducts() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllProducts, []),
            returnValue: _i5.Stream<List<_i2.ProductEntity>>.empty(),
          )
          as _i5.Stream<List<_i2.ProductEntity>>);

  @override
  _i5.Stream<List<_i2.ProductEntity>> watchPaginatedProducts({
    required int? limit,
    required int? offset,
    int? categoryId,
    String? searchTerm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchPaginatedProducts, [], {
              #limit: limit,
              #offset: offset,
              #categoryId: categoryId,
              #searchTerm: searchTerm,
            }),
            returnValue: _i5.Stream<List<_i2.ProductEntity>>.empty(),
          )
          as _i5.Stream<List<_i2.ProductEntity>>);

  @override
  _i5.Stream<List<_i2.ProductEntity>> watchProductsByCategoryId(
    int? categoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchProductsByCategoryId, [categoryId]),
            returnValue: _i5.Stream<List<_i2.ProductEntity>>.empty(),
          )
          as _i5.Stream<List<_i2.ProductEntity>>);

  @override
  _i5.Stream<_i2.ProductEntity?> watchProductById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchProductById, [id]),
            returnValue: _i5.Stream<_i2.ProductEntity?>.empty(),
          )
          as _i5.Stream<_i2.ProductEntity?>);

  @override
  _i5.Future<_i2.ProductEntity?> getProductById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i5.Future<_i2.ProductEntity?>.value(),
          )
          as _i5.Future<_i2.ProductEntity?>);

  @override
  _i5.Future<_i2.ProductEntity?> getProductBySku(String? sku) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBySku, [sku]),
            returnValue: _i5.Future<_i2.ProductEntity?>.value(),
          )
          as _i5.Future<_i2.ProductEntity?>);

  @override
  _i5.Future<List<String>> distinctPrepStations() =>
      (super.noSuchMethod(
            Invocation.method(#distinctPrepStations, []),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<int> getProductsCount({int? categoryId, String? searchTerm}) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsCount, [], {
              #categoryId: categoryId,
              #searchTerm: searchTerm,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> insertProduct(_i2.ProductsTableCompanion? companion) =>
      (super.noSuchMethod(
            Invocation.method(#insertProduct, [companion]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<bool> updateProduct(
    int? id,
    _i2.ProductsTableCompanion? companion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [id, companion]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> softDeleteProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteProduct, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> restoreProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#restoreProduct, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> hardDeleteProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeleteProduct, [id]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Stream<T> createStream<T extends Object>(
    _i4.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i5.Stream<T>.empty(),
          )
          as _i5.Stream<T>);

  @override
  T alias<T, D>(_i3.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i7.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Stream<Set<_i3.TableUpdate>> tableUpdates([
    _i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i5.Stream<Set<_i3.TableUpdate>>.empty(),
          )
          as _i5.Stream<Set<_i3.TableUpdate>>);

  @override
  _i5.Future<T> doWhenOpened<T>(
    _i5.FutureOr<T> Function(_i3.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_6<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i5.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_7<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
    _i3.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_8<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_9<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_10<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
    Iterable<_i3.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_11<_i3.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_12<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i3.DeleteStatement<T, D>);

  @override
  _i5.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<List<_i3.QueryRow>>.value(<_i3.QueryRow>[]),
          )
          as _i5.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_13<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_13<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i5.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> transaction<T>(
    _i5.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_6<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<T> exclusively<T>(_i5.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_6<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<void> batch(_i5.FutureOr<void> Function(_i3.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> runWithInterceptor<T>(
    _i5.Future<T> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_6<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_14(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_14(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [InventoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryRepository extends _i1.Mock
    implements _i8.InventoryRepository {
  MockInventoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<({int productId, int quantity})>> watchAllStocks() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllStocks, []),
            returnValue:
                _i5.Stream<List<({int productId, int quantity})>>.empty(),
          )
          as _i5.Stream<List<({int productId, int quantity})>>);

  @override
  _i5.Stream<
    List<({String name, int productId, int quantity, bool trackStock})>
  >
  watchStockLevels() =>
      (super.noSuchMethod(
            Invocation.method(#watchStockLevels, []),
            returnValue:
                _i5.Stream<
                  List<
                    ({
                      String name,
                      int productId,
                      int quantity,
                      bool trackStock,
                    })
                  >
                >.empty(),
          )
          as _i5.Stream<
            List<({String name, int productId, int quantity, bool trackStock})>
          >);

  @override
  _i5.Stream<({int productId, int quantity})?> watchStockByProductId(
    int? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchStockByProductId, [productId]),
            returnValue: _i5.Stream<({int productId, int quantity})?>.empty(),
          )
          as _i5.Stream<({int productId, int quantity})?>);

  @override
  _i5.Stream<List<({int productId, int quantity})>> watchLowStocks(
    int? threshold,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchLowStocks, [threshold]),
            returnValue:
                _i5.Stream<List<({int productId, int quantity})>>.empty(),
          )
          as _i5.Stream<List<({int productId, int quantity})>>);

  @override
  _i5.Stream<
    List<
      ({
        int id,
        int productId,
        int quantityChange,
        String reason,
        DateTime timestamp,
      })
    >
  >
  watchMovementsByProductId(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#watchMovementsByProductId, [productId]),
            returnValue:
                _i5.Stream<
                  List<
                    ({
                      int id,
                      int productId,
                      int quantityChange,
                      String reason,
                      DateTime timestamp,
                    })
                  >
                >.empty(),
          )
          as _i5.Stream<
            List<
              ({
                int id,
                int productId,
                int quantityChange,
                String reason,
                DateTime timestamp,
              })
            >
          >);

  @override
  _i5.Future<_i9.Result<int>> getStockQuantity(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getStockQuantity, [productId]),
            returnValue: _i5.Future<_i9.Result<int>>.value(
              _i7.dummyValue<_i9.Result<int>>(
                this,
                Invocation.method(#getStockQuantity, [productId]),
              ),
            ),
          )
          as _i5.Future<_i9.Result<int>>);

  @override
  _i5.Future<_i9.Result<({int productId, int quantity})?>> getStockByProductId(
    int? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getStockByProductId, [productId]),
            returnValue:
                _i5.Future<_i9.Result<({int productId, int quantity})?>>.value(
                  _i7.dummyValue<_i9.Result<({int productId, int quantity})?>>(
                    this,
                    Invocation.method(#getStockByProductId, [productId]),
                  ),
                ),
          )
          as _i5.Future<_i9.Result<({int productId, int quantity})?>>);

  @override
  _i5.Future<_i9.Result<int>> getStocksCount() =>
      (super.noSuchMethod(
            Invocation.method(#getStocksCount, []),
            returnValue: _i5.Future<_i9.Result<int>>.value(
              _i7.dummyValue<_i9.Result<int>>(
                this,
                Invocation.method(#getStocksCount, []),
              ),
            ),
          )
          as _i5.Future<_i9.Result<int>>);

  @override
  _i5.Future<
    _i9.Result<
      List<
        ({
          int id,
          int productId,
          int quantityChange,
          String reason,
          DateTime timestamp,
        })
      >
    >
  >
  getMovementHistory({
    int? productId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMovementHistory, [], {
              #productId: productId,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue:
                _i5.Future<
                  _i9.Result<
                    List<
                      ({
                        int id,
                        int productId,
                        int quantityChange,
                        String reason,
                        DateTime timestamp,
                      })
                    >
                  >
                >.value(
                  _i7.dummyValue<
                    _i9.Result<
                      List<
                        ({
                          int id,
                          int productId,
                          int quantityChange,
                          String reason,
                          DateTime timestamp,
                        })
                      >
                    >
                  >(
                    this,
                    Invocation.method(#getMovementHistory, [], {
                      #productId: productId,
                      #startDate: startDate,
                      #endDate: endDate,
                    }),
                  ),
                ),
          )
          as _i5.Future<
            _i9.Result<
              List<
                ({
                  int id,
                  int productId,
                  int quantityChange,
                  String reason,
                  DateTime timestamp,
                })
              >
            >
          >);

  @override
  _i5.Future<_i9.Result<({int productId, int quantity})>> adjustStock({
    required int? productId,
    required int? delta,
    required String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#adjustStock, [], {
              #productId: productId,
              #delta: delta,
              #reason: reason,
            }),
            returnValue:
                _i5.Future<_i9.Result<({int productId, int quantity})>>.value(
                  _i7.dummyValue<_i9.Result<({int productId, int quantity})>>(
                    this,
                    Invocation.method(#adjustStock, [], {
                      #productId: productId,
                      #delta: delta,
                      #reason: reason,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i9.Result<({int productId, int quantity})>>);

  @override
  _i5.Future<_i9.Result<({int productId, int quantity})>> setStock({
    required int? productId,
    required int? quantity,
    required String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setStock, [], {
              #productId: productId,
              #quantity: quantity,
              #reason: reason,
            }),
            returnValue:
                _i5.Future<_i9.Result<({int productId, int quantity})>>.value(
                  _i7.dummyValue<_i9.Result<({int productId, int quantity})>>(
                    this,
                    Invocation.method(#setStock, [], {
                      #productId: productId,
                      #quantity: quantity,
                      #reason: reason,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i9.Result<({int productId, int quantity})>>);

  @override
  _i5.Future<_i9.Result<({int productId, int quantity})>> decrementForOrder({
    required int? productId,
    required int? quantity,
    required int? orderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decrementForOrder, [], {
              #productId: productId,
              #quantity: quantity,
              #orderId: orderId,
            }),
            returnValue:
                _i5.Future<_i9.Result<({int productId, int quantity})>>.value(
                  _i7.dummyValue<_i9.Result<({int productId, int quantity})>>(
                    this,
                    Invocation.method(#decrementForOrder, [], {
                      #productId: productId,
                      #quantity: quantity,
                      #orderId: orderId,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i9.Result<({int productId, int quantity})>>);

  @override
  _i5.Future<_i9.Result<({int productId, int quantity})>>
  restoreForVoidedOrder({
    required int? productId,
    required int? quantity,
    required int? orderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#restoreForVoidedOrder, [], {
              #productId: productId,
              #quantity: quantity,
              #orderId: orderId,
            }),
            returnValue:
                _i5.Future<_i9.Result<({int productId, int quantity})>>.value(
                  _i7.dummyValue<_i9.Result<({int productId, int quantity})>>(
                    this,
                    Invocation.method(#restoreForVoidedOrder, [], {
                      #productId: productId,
                      #quantity: quantity,
                      #orderId: orderId,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i9.Result<({int productId, int quantity})>>);

  @override
  _i5.Future<_i9.Result<void>> initializeStock({
    required int? productId,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initializeStock, [], {
              #productId: productId,
              #quantity: quantity,
            }),
            returnValue: _i5.Future<_i9.Result<void>>.value(
              _i7.dummyValue<_i9.Result<void>>(
                this,
                Invocation.method(#initializeStock, [], {
                  #productId: productId,
                  #quantity: quantity,
                }),
              ),
            ),
          )
          as _i5.Future<_i9.Result<void>>);

  @override
  _i5.Future<_i9.Result<void>> softDeleteStock(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteStock, [productId]),
            returnValue: _i5.Future<_i9.Result<void>>.value(
              _i7.dummyValue<_i9.Result<void>>(
                this,
                Invocation.method(#softDeleteStock, [productId]),
              ),
            ),
          )
          as _i5.Future<_i9.Result<void>>);

  @override
  _i5.Future<_i9.Result<void>> restoreStock(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreStock, [productId]),
            returnValue: _i5.Future<_i9.Result<void>>.value(
              _i7.dummyValue<_i9.Result<void>>(
                this,
                Invocation.method(#restoreStock, [productId]),
              ),
            ),
          )
          as _i5.Future<_i9.Result<void>>);
}

/// A class which mocks [ModifiersDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockModifiersDao extends _i1.Mock implements _i10.ModifiersDao {
  MockModifiersDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AgoraDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeAgoraDatabase_0(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i2.AgoraDatabase);

  @override
  _i3.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_1(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i3.DatabaseConnection);

  @override
  _i3.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_2(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i3.DriftDatabaseOptions);

  @override
  _i3.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i7.dummyValue<_i3.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i3.SqlTypes);

  @override
  _i3.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_3(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i3.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_4(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i4.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_5(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i3.DatabaseConnectionUser);

  @override
  _i5.Stream<List<_i2.ModifierEntity>> watchAllModifiers() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllModifiers, []),
            returnValue: _i5.Stream<List<_i2.ModifierEntity>>.empty(),
          )
          as _i5.Stream<List<_i2.ModifierEntity>>);

  @override
  _i5.Stream<List<_i2.ModifierEntity>> watchPaginatedModifiers({
    required int? limit,
    required int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchPaginatedModifiers, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i5.Stream<List<_i2.ModifierEntity>>.empty(),
          )
          as _i5.Stream<List<_i2.ModifierEntity>>);

  @override
  _i5.Stream<_i2.ModifierEntity?> watchModifierById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchModifierById, [id]),
            returnValue: _i5.Stream<_i2.ModifierEntity?>.empty(),
          )
          as _i5.Stream<_i2.ModifierEntity?>);

  @override
  _i5.Future<_i2.ModifierEntity?> getModifierById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getModifierById, [id]),
            returnValue: _i5.Future<_i2.ModifierEntity?>.value(),
          )
          as _i5.Future<_i2.ModifierEntity?>);

  @override
  _i5.Future<int> getModifiersCount() =>
      (super.noSuchMethod(
            Invocation.method(#getModifiersCount, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> insertModifier(_i2.ModifiersTableCompanion? companion) =>
      (super.noSuchMethod(
            Invocation.method(#insertModifier, [companion]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<bool> updateModifier(
    int? id,
    _i2.ModifiersTableCompanion? companion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateModifier, [id, companion]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> softDeleteModifier(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteModifier, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> restoreModifier(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#restoreModifier, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> hardDeleteModifier(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeleteModifier, [id]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Stream<List<_i2.ModifierOptionEntity>> watchOptionsByModifierId(
    int? modifierId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchOptionsByModifierId, [modifierId]),
            returnValue: _i5.Stream<List<_i2.ModifierOptionEntity>>.empty(),
          )
          as _i5.Stream<List<_i2.ModifierOptionEntity>>);

  @override
  _i5.Future<List<_i2.ModifierOptionEntity>> getOptionsByModifierId(
    int? modifierId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOptionsByModifierId, [modifierId]),
            returnValue: _i5.Future<List<_i2.ModifierOptionEntity>>.value(
              <_i2.ModifierOptionEntity>[],
            ),
          )
          as _i5.Future<List<_i2.ModifierOptionEntity>>);

  @override
  _i5.Future<_i2.ModifierOptionEntity?> getModifierOptionById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getModifierOptionById, [id]),
            returnValue: _i5.Future<_i2.ModifierOptionEntity?>.value(),
          )
          as _i5.Future<_i2.ModifierOptionEntity?>);

  @override
  _i5.Future<int> insertModifierOption(
    _i2.ModifierOptionsTableCompanion? companion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertModifierOption, [companion]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<bool> updateModifierOption(
    int? id,
    _i2.ModifierOptionsTableCompanion? companion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateModifierOption, [id, companion]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> softDeleteModifierOption(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteModifierOption, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> hardDeleteModifierOption(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeleteModifierOption, [id]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> hardDeleteOptionsByModifierId(int? modifierId) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeleteOptionsByModifierId, [modifierId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Stream<List<_i2.ModifierEntity>> watchModifiersByProductId(
    int? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchModifiersByProductId, [productId]),
            returnValue: _i5.Stream<List<_i2.ModifierEntity>>.empty(),
          )
          as _i5.Stream<List<_i2.ModifierEntity>>);

  @override
  _i5.Future<List<_i2.ModifierEntity>> getModifiersByProductId(
    int? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getModifiersByProductId, [productId]),
            returnValue: _i5.Future<List<_i2.ModifierEntity>>.value(
              <_i2.ModifierEntity>[],
            ),
          )
          as _i5.Future<List<_i2.ModifierEntity>>);

  @override
  _i5.Future<List<int>> getProductIdsByModifierId(int? modifierId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductIdsByModifierId, [modifierId]),
            returnValue: _i5.Future<List<int>>.value(<int>[]),
          )
          as _i5.Future<List<int>>);

  @override
  _i5.Future<int> linkProductToModifier({
    required int? productId,
    required int? modifierId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkProductToModifier, [], {
              #productId: productId,
              #modifierId: modifierId,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> unlinkProductFromModifier({
    required int? productId,
    required int? modifierId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkProductFromModifier, [], {
              #productId: productId,
              #modifierId: modifierId,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> unlinkAllModifiersFromProduct(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkAllModifiersFromProduct, [productId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> unlinkAllProductsFromModifier(int? modifierId) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkAllProductsFromModifier, [modifierId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Stream<T> createStream<T extends Object>(
    _i4.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i5.Stream<T>.empty(),
          )
          as _i5.Stream<T>);

  @override
  T alias<T, D>(_i3.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i7.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Stream<Set<_i3.TableUpdate>> tableUpdates([
    _i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i5.Stream<Set<_i3.TableUpdate>>.empty(),
          )
          as _i5.Stream<Set<_i3.TableUpdate>>);

  @override
  _i5.Future<T> doWhenOpened<T>(
    _i5.FutureOr<T> Function(_i3.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_6<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i5.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_7<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
    _i3.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_8<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_9<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_10<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
    Iterable<_i3.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_11<_i3.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_12<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i3.DeleteStatement<T, D>);

  @override
  _i5.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<List<_i3.QueryRow>>.value(<_i3.QueryRow>[]),
          )
          as _i5.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_13<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_13<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i5.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> transaction<T>(
    _i5.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_6<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<T> exclusively<T>(_i5.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_6<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<void> batch(_i5.FutureOr<void> Function(_i3.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> runWithInterceptor<T>(
    _i5.Future<T> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_6<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_14(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_14(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
