name: feature_settings
description: Application settings feature
publish_to: none
resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.5'

dependencies:
  auto_route: ^11.1.0
  bloc_exports:
    path: ../../packages/bloc
  database:
    path: ../../packages/database
  drift: ^2.30.0
  errors:
    path: ../../packages/errors
  feature_discounts:
    path: ../discounts
  feature_products:
    path: ../products
  flutter:
    sdk: flutter
  i18n:
    path: ../../packages/i18n
  logger:
    path: ../../packages/logger
  printing:
    path: ../../packages/printing
  result:
    path: ../../packages/result
  talker: ^5.1.9
  ui_kit:
    path: ../../packages/ui_kit
  utils:
    path: ../../packages/utils

dev_dependencies:
  flutter_test:
    sdk: flutter
