// Mocks generated by Mockito 5.4.6 from annotations
// in feature_orders/test/data/repositories/orders_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sync_engine/src/model/outbox_entry.dart' as _i7;
import 'package:sync_engine/src/model/sync_status.dart' as _i4;
import 'package:sync_engine/src/sync_handler.dart' as _i6;
import 'package:sync_engine/src/sync_manager.dart' as _i2;
import 'package:sync_engine/src/websocket/sync_message.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SyncManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncManager extends _i1.Mock implements _i2.SyncManager {
  MockSyncManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.SyncStatus> get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i3.Stream<_i4.SyncStatus>.empty(),
          )
          as _i3.Stream<_i4.SyncStatus>);

  @override
  _i3.Stream<_i5.SyncMessage> get inboundMessages =>
      (super.noSuchMethod(
            Invocation.getter(#inboundMessages),
            returnValue: _i3.Stream<_i5.SyncMessage>.empty(),
          )
          as _i3.Stream<_i5.SyncMessage>);

  @override
  void registerHandler(_i6.SyncHandler? handler) => super.noSuchMethod(
    Invocation.method(#registerHandler, [handler]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> start({String? webSocketUrl, String? authToken}) =>
      (super.noSuchMethod(
            Invocation.method(#start, [], {
              #webSocketUrl: webSocketUrl,
              #authToken: authToken,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> enqueue({
    required String? entityType,
    required _i7.OutboxOperation? operation,
    required String? entityLocalId,
    required Map<String, dynamic>? payload,
    String? remoteId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enqueue, [], {
              #entityType: entityType,
              #operation: operation,
              #entityLocalId: entityLocalId,
              #payload: payload,
              #remoteId: remoteId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void subscribe(String? topic) => super.noSuchMethod(
    Invocation.method(#subscribe, [topic]),
    returnValueForMissingStub: null,
  );

  @override
  void unsubscribe(String? topic) => super.noSuchMethod(
    Invocation.method(#unsubscribe, [topic]),
    returnValueForMissingStub: null,
  );
}
