// Mocks generated by Mockito 5.4.6 from annotations
// in agora/test/products/blocs/product_detail/product_detail_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:agora/core/misc/result.dart' as _i5;
import 'package:agora/products/models/modifier_group/modifier_group.dart'
    as _i8;
import 'package:agora/products/models/modifier_option/modifier_option.dart'
    as _i9;
import 'package:agora/products/models/product/product.dart' as _i4;
import 'package:agora/products/repositories/modifiers_repository.dart' as _i7;
import 'package:agora/products/repositories/products_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProductsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRepository extends _i1.Mock
    implements _i2.ProductsRepository {
  MockProductsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Product>> watchAllProducts() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllProducts, []),
            returnValue: _i3.Stream<List<_i4.Product>>.empty(),
          )
          as _i3.Stream<List<_i4.Product>>);

  @override
  _i3.Stream<List<_i4.Product>> watchProductsByCategory(int? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#watchProductsByCategory, [categoryId]),
            returnValue: _i3.Stream<List<_i4.Product>>.empty(),
          )
          as _i3.Stream<List<_i4.Product>>);

  @override
  _i3.Stream<_i4.Product?> watchProductById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchProductById, [id]),
            returnValue: _i3.Stream<_i4.Product?>.empty(),
          )
          as _i3.Stream<_i4.Product?>);

  @override
  _i3.Future<_i5.Result<_i4.Product?>> getProductById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i3.Future<_i5.Result<_i4.Product?>>.value(
              _i6.dummyValue<_i5.Result<_i4.Product?>>(
                this,
                Invocation.method(#getProductById, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.Product?>>);

  @override
  _i3.Future<_i5.Result<_i4.Product?>> getProductBySku(String? sku) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBySku, [sku]),
            returnValue: _i3.Future<_i5.Result<_i4.Product?>>.value(
              _i6.dummyValue<_i5.Result<_i4.Product?>>(
                this,
                Invocation.method(#getProductBySku, [sku]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.Product?>>);

  @override
  _i3.Future<_i5.Result<int>> getProductsCount({
    int? categoryId,
    String? searchTerm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsCount, [], {
              #categoryId: categoryId,
              #searchTerm: searchTerm,
            }),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i6.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#getProductsCount, [], {
                  #categoryId: categoryId,
                  #searchTerm: searchTerm,
                }),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);

  @override
  _i3.Future<_i5.Result<_i4.Product>> createProduct(_i4.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#createProduct, [product]),
            returnValue: _i3.Future<_i5.Result<_i4.Product>>.value(
              _i6.dummyValue<_i5.Result<_i4.Product>>(
                this,
                Invocation.method(#createProduct, [product]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.Product>>);

  @override
  _i3.Future<_i5.Result<_i4.Product>> updateProduct(_i4.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i3.Future<_i5.Result<_i4.Product>>.value(
              _i6.dummyValue<_i5.Result<_i4.Product>>(
                this,
                Invocation.method(#updateProduct, [product]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.Product>>);

  @override
  _i3.Future<_i5.Result<int>> deleteProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i6.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#deleteProduct, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);

  @override
  _i3.Future<_i5.Result<bool>> restoreProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#restoreProduct, [id]),
            returnValue: _i3.Future<_i5.Result<bool>>.value(
              _i6.dummyValue<_i5.Result<bool>>(
                this,
                Invocation.method(#restoreProduct, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<bool>>);
}

/// A class which mocks [ModifiersRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockModifiersRepository extends _i1.Mock
    implements _i7.ModifiersRepository {
  MockModifiersRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i8.ModifierGroup>> watchAllModifiers() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllModifiers, []),
            returnValue: _i3.Stream<List<_i8.ModifierGroup>>.empty(),
          )
          as _i3.Stream<List<_i8.ModifierGroup>>);

  @override
  _i3.Stream<List<_i8.ModifierGroup>> watchModifiersByProductId(
    int? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchModifiersByProductId, [productId]),
            returnValue: _i3.Stream<List<_i8.ModifierGroup>>.empty(),
          )
          as _i3.Stream<List<_i8.ModifierGroup>>);

  @override
  _i3.Stream<_i8.ModifierGroup?> watchModifierById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchModifierById, [id]),
            returnValue: _i3.Stream<_i8.ModifierGroup?>.empty(),
          )
          as _i3.Stream<_i8.ModifierGroup?>);

  @override
  _i3.Future<_i5.Result<_i8.ModifierGroup?>> getModifierById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getModifierById, [id]),
            returnValue: _i3.Future<_i5.Result<_i8.ModifierGroup?>>.value(
              _i6.dummyValue<_i5.Result<_i8.ModifierGroup?>>(
                this,
                Invocation.method(#getModifierById, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i8.ModifierGroup?>>);

  @override
  _i3.Future<_i5.Result<List<_i8.ModifierGroup>>> getModifiersByProductId(
    int? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getModifiersByProductId, [productId]),
            returnValue: _i3.Future<_i5.Result<List<_i8.ModifierGroup>>>.value(
              _i6.dummyValue<_i5.Result<List<_i8.ModifierGroup>>>(
                this,
                Invocation.method(#getModifiersByProductId, [productId]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<List<_i8.ModifierGroup>>>);

  @override
  _i3.Future<_i5.Result<int>> getModifiersCount() =>
      (super.noSuchMethod(
            Invocation.method(#getModifiersCount, []),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i6.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#getModifiersCount, []),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);

  @override
  _i3.Future<_i5.Result<_i8.ModifierGroup>> createModifier(
    _i8.ModifierGroup? modifier,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createModifier, [modifier]),
            returnValue: _i3.Future<_i5.Result<_i8.ModifierGroup>>.value(
              _i6.dummyValue<_i5.Result<_i8.ModifierGroup>>(
                this,
                Invocation.method(#createModifier, [modifier]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i8.ModifierGroup>>);

  @override
  _i3.Future<_i5.Result<_i8.ModifierGroup>> updateModifier(
    _i8.ModifierGroup? modifier,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateModifier, [modifier]),
            returnValue: _i3.Future<_i5.Result<_i8.ModifierGroup>>.value(
              _i6.dummyValue<_i5.Result<_i8.ModifierGroup>>(
                this,
                Invocation.method(#updateModifier, [modifier]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i8.ModifierGroup>>);

  @override
  _i3.Future<_i5.Result<int>> deleteModifier(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteModifier, [id]),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i6.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#deleteModifier, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);

  @override
  _i3.Future<_i5.Result<_i9.ModifierOption>> createModifierOption({
    required int? modifierId,
    required _i9.ModifierOption? option,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createModifierOption, [], {
              #modifierId: modifierId,
              #option: option,
            }),
            returnValue: _i3.Future<_i5.Result<_i9.ModifierOption>>.value(
              _i6.dummyValue<_i5.Result<_i9.ModifierOption>>(
                this,
                Invocation.method(#createModifierOption, [], {
                  #modifierId: modifierId,
                  #option: option,
                }),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i9.ModifierOption>>);

  @override
  _i3.Future<_i5.Result<_i9.ModifierOption>> updateModifierOption(
    _i9.ModifierOption? option,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateModifierOption, [option]),
            returnValue: _i3.Future<_i5.Result<_i9.ModifierOption>>.value(
              _i6.dummyValue<_i5.Result<_i9.ModifierOption>>(
                this,
                Invocation.method(#updateModifierOption, [option]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i9.ModifierOption>>);

  @override
  _i3.Future<_i5.Result<int>> deleteModifierOption(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteModifierOption, [id]),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i6.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#deleteModifierOption, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);

  @override
  _i3.Future<_i5.Result<void>> linkModifierToProduct({
    required int? modifierId,
    required int? productId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkModifierToProduct, [], {
              #modifierId: modifierId,
              #productId: productId,
            }),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#linkModifierToProduct, [], {
                  #modifierId: modifierId,
                  #productId: productId,
                }),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> unlinkModifierFromProduct({
    required int? modifierId,
    required int? productId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkModifierFromProduct, [], {
              #modifierId: modifierId,
              #productId: productId,
            }),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#unlinkModifierFromProduct, [], {
                  #modifierId: modifierId,
                  #productId: productId,
                }),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> setProductModifiers({
    required int? productId,
    required List<int>? modifierIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setProductModifiers, [], {
              #productId: productId,
              #modifierIds: modifierIds,
            }),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#setProductModifiers, [], {
                  #productId: productId,
                  #modifierIds: modifierIds,
                }),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);
}
