// Mocks generated by Mockito 5.4.6 from annotations
// in feature_products/test/blocs/combos/combos_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:catalog/models/combo.dart' as _i4;
import 'package:catalog/repositories/combos_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:result/result.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CombosRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCombosRepository extends _i1.Mock implements _i2.CombosRepository {
  MockCombosRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Combo>> watchAllCombos() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllCombos, []),
            returnValue: _i3.Stream<List<_i4.Combo>>.empty(),
          )
          as _i3.Stream<List<_i4.Combo>>);

  @override
  _i3.Stream<_i4.Combo?> watchComboById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchComboById, [id]),
            returnValue: _i3.Stream<_i4.Combo?>.empty(),
          )
          as _i3.Stream<_i4.Combo?>);

  @override
  _i3.Future<_i5.Result<_i4.Combo?>> getComboById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getComboById, [id]),
            returnValue: _i3.Future<_i5.Result<_i4.Combo?>>.value(
              _i6.dummyValue<_i5.Result<_i4.Combo?>>(
                this,
                Invocation.method(#getComboById, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.Combo?>>);

  @override
  _i3.Future<_i5.Result<int>> getCombosCount() =>
      (super.noSuchMethod(
            Invocation.method(#getCombosCount, []),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i6.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#getCombosCount, []),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);

  @override
  _i3.Future<_i5.Result<_i4.Combo>> createCombo(_i4.Combo? combo) =>
      (super.noSuchMethod(
            Invocation.method(#createCombo, [combo]),
            returnValue: _i3.Future<_i5.Result<_i4.Combo>>.value(
              _i6.dummyValue<_i5.Result<_i4.Combo>>(
                this,
                Invocation.method(#createCombo, [combo]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.Combo>>);

  @override
  _i3.Future<_i5.Result<_i4.Combo>> updateCombo(_i4.Combo? combo) =>
      (super.noSuchMethod(
            Invocation.method(#updateCombo, [combo]),
            returnValue: _i3.Future<_i5.Result<_i4.Combo>>.value(
              _i6.dummyValue<_i5.Result<_i4.Combo>>(
                this,
                Invocation.method(#updateCombo, [combo]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.Combo>>);

  @override
  _i3.Future<_i5.Result<int>> deleteCombo(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCombo, [id]),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i6.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#deleteCombo, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);
}
