// Mocks generated by Mockito 5.4.6 from annotations
// in agora_workspace/test/orders/blocs/active_order/active_order_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bloc_exports/bloc_exports.dart' as _i8;
import 'package:order_management/models/order.dart' as _i5;
import 'package:order_management/repositories/orders_repository.dart' as _i3;
import 'package:app_settings/blocs/settings_cubit.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:result/result.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSettingsState_0 extends _i1.SmartFake implements _i2.SettingsState {
  _FakeSettingsState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrdersRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrdersRepository extends _i1.Mock implements _i3.OrdersRepository {
  MockOrdersRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i5.Order>> watchAllOrders() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllOrders, []),
            returnValue: _i4.Stream<List<_i5.Order>>.empty(),
          )
          as _i4.Stream<List<_i5.Order>>);

  @override
  _i4.Stream<List<_i5.Order>> watchPendingOrders() =>
      (super.noSuchMethod(
            Invocation.method(#watchPendingOrders, []),
            returnValue: _i4.Stream<List<_i5.Order>>.empty(),
          )
          as _i4.Stream<List<_i5.Order>>);

  @override
  _i4.Stream<List<_i5.Order>> watchCompletedOrders() =>
      (super.noSuchMethod(
            Invocation.method(#watchCompletedOrders, []),
            returnValue: _i4.Stream<List<_i5.Order>>.empty(),
          )
          as _i4.Stream<List<_i5.Order>>);

  @override
  _i4.Stream<_i5.Order?> watchOrderById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchOrderById, [id]),
            returnValue: _i4.Stream<_i5.Order?>.empty(),
          )
          as _i4.Stream<_i5.Order?>);

  @override
  _i4.Stream<List<_i5.Order>> watchOrdersByDateRange({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchOrdersByDateRange, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i4.Stream<List<_i5.Order>>.empty(),
          )
          as _i4.Stream<List<_i5.Order>>);

  @override
  _i4.Future<_i6.Result<_i5.Order?>> getOrderById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderById, [id]),
            returnValue: _i4.Future<_i6.Result<_i5.Order?>>.value(
              _i7.dummyValue<_i6.Result<_i5.Order?>>(
                this,
                Invocation.method(#getOrderById, [id]),
              ),
            ),
          )
          as _i4.Future<_i6.Result<_i5.Order?>>);

  @override
  _i4.Future<_i6.Result<int>> getOrdersCount({
    _i5.OrderStatus? status,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrdersCount, [], {
              #status: status,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i4.Future<_i6.Result<int>>.value(
              _i7.dummyValue<_i6.Result<int>>(
                this,
                Invocation.method(#getOrdersCount, [], {
                  #status: status,
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
          )
          as _i4.Future<_i6.Result<int>>);

  @override
  _i4.Future<_i6.Result<int>> getTotalRevenue({
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalRevenue, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i4.Future<_i6.Result<int>>.value(
              _i7.dummyValue<_i6.Result<int>>(
                this,
                Invocation.method(#getTotalRevenue, [], {
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
          )
          as _i4.Future<_i6.Result<int>>);

  @override
  _i4.Future<_i6.Result<int>> getTotalDiscounts({
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalDiscounts, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i4.Future<_i6.Result<int>>.value(
              _i7.dummyValue<_i6.Result<int>>(
                this,
                Invocation.method(#getTotalDiscounts, [], {
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
          )
          as _i4.Future<_i6.Result<int>>);

  @override
  _i4.Future<_i6.Result<_i5.Order>> createOrder(_i5.Order? order) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [order]),
            returnValue: _i4.Future<_i6.Result<_i5.Order>>.value(
              _i7.dummyValue<_i6.Result<_i5.Order>>(
                this,
                Invocation.method(#createOrder, [order]),
              ),
            ),
          )
          as _i4.Future<_i6.Result<_i5.Order>>);

  @override
  _i4.Future<_i6.Result<_i5.Order>> updateOrder(_i5.Order? order) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrder, [order]),
            returnValue: _i4.Future<_i6.Result<_i5.Order>>.value(
              _i7.dummyValue<_i6.Result<_i5.Order>>(
                this,
                Invocation.method(#updateOrder, [order]),
              ),
            ),
          )
          as _i4.Future<_i6.Result<_i5.Order>>);

  @override
  _i4.Future<_i6.Result<_i5.Order>> completeOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#completeOrder, [id]),
            returnValue: _i4.Future<_i6.Result<_i5.Order>>.value(
              _i7.dummyValue<_i6.Result<_i5.Order>>(
                this,
                Invocation.method(#completeOrder, [id]),
              ),
            ),
          )
          as _i4.Future<_i6.Result<_i5.Order>>);

  @override
  _i4.Future<_i6.Result<_i5.Order>> voidOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#voidOrder, [id]),
            returnValue: _i4.Future<_i6.Result<_i5.Order>>.value(
              _i7.dummyValue<_i6.Result<_i5.Order>>(
                this,
                Invocation.method(#voidOrder, [id]),
              ),
            ),
          )
          as _i4.Future<_i6.Result<_i5.Order>>);

  @override
  _i4.Future<_i6.Result<int>> deleteOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOrder, [id]),
            returnValue: _i4.Future<_i6.Result<int>>.value(
              _i7.dummyValue<_i6.Result<int>>(
                this,
                Invocation.method(#deleteOrder, [id]),
              ),
            ),
          )
          as _i4.Future<_i6.Result<int>>);

  @override
  _i4.Stream<List<_i5.Order>> watchOrdersByStatus(
    _i5.OrderStatus? orderStatus,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchOrdersByStatus, [orderStatus]),
            returnValue: _i4.Stream<List<_i5.Order>>.empty(),
          )
          as _i4.Stream<List<_i5.Order>>);
}

/// A class which mocks [SettingsCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsCubit extends _i1.Mock implements _i2.SettingsCubit {
  MockSettingsCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SettingsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSettingsState_0(this, Invocation.getter(#state)),
          )
          as _i2.SettingsState);

  @override
  _i4.Stream<_i2.SettingsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i2.SettingsState>.empty(),
          )
          as _i4.Stream<_i2.SettingsState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i4.Future<void> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> update(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#update, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#updateInt, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#updateBool, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#updateDouble, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  bool getBool(String? key, {bool? defaultValue = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key], {#defaultValue: defaultValue}),
            returnValue: false,
          )
          as bool);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  _i4.Future<void> delete(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> reset() =>
      (super.noSuchMethod(
            Invocation.method(#reset, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void emit(_i2.SettingsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i8.Change<_i2.SettingsState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
