// Mocks generated by Mockito 5.4.6 from annotations
// in agora_workspace/test/orders/blocs/order_detail/order_detail_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:feature_inventory/domain/repositories/inventory_repository.dart'
    as _i7;
import 'package:feature_orders/domain/models/order.dart' as _i4;
import 'package:feature_orders/domain/repositories/orders_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:result/result.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OrdersRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrdersRepository extends _i1.Mock implements _i2.OrdersRepository {
  MockOrdersRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Order>> watchAllOrders() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllOrders, []),
            returnValue: _i3.Stream<List<_i4.Order>>.empty(),
          )
          as _i3.Stream<List<_i4.Order>>);

  @override
  _i3.Stream<List<_i4.Order>> watchPendingOrders() =>
      (super.noSuchMethod(
            Invocation.method(#watchPendingOrders, []),
            returnValue: _i3.Stream<List<_i4.Order>>.empty(),
          )
          as _i3.Stream<List<_i4.Order>>);

  @override
  _i3.Stream<List<_i4.Order>> watchCompletedOrders() =>
      (super.noSuchMethod(
            Invocation.method(#watchCompletedOrders, []),
            returnValue: _i3.Stream<List<_i4.Order>>.empty(),
          )
          as _i3.Stream<List<_i4.Order>>);

  @override
  _i3.Stream<_i4.Order?> watchOrderById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchOrderById, [id]),
            returnValue: _i3.Stream<_i4.Order?>.empty(),
          )
          as _i3.Stream<_i4.Order?>);

  @override
  _i3.Stream<List<_i4.Order>> watchOrdersByDateRange({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchOrdersByDateRange, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i3.Stream<List<_i4.Order>>.empty(),
          )
          as _i3.Stream<List<_i4.Order>>);

  @override
  _i3.Future<_i5.Result<_i4.Order?>> getOrderById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderById, [id]),
            returnValue: _i3.Future<_i5.Result<_i4.Order?>>.value(
              _i6.dummyValue<_i5.Result<_i4.Order?>>(
                this,
                Invocation.method(#getOrderById, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.Order?>>);

  @override
  _i3.Future<_i5.Result<int>> getOrdersCount({
    _i4.OrderStatus? status,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrdersCount, [], {
              #status: status,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i6.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#getOrdersCount, [], {
                  #status: status,
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);

  @override
  _i3.Future<_i5.Result<int>> getTotalRevenue({
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalRevenue, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i6.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#getTotalRevenue, [], {
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);

  @override
  _i3.Future<_i5.Result<int>> getTotalDiscounts({
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalDiscounts, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i6.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#getTotalDiscounts, [], {
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);

  @override
  _i3.Future<_i5.Result<_i4.Order>> createOrder(_i4.Order? order) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [order]),
            returnValue: _i3.Future<_i5.Result<_i4.Order>>.value(
              _i6.dummyValue<_i5.Result<_i4.Order>>(
                this,
                Invocation.method(#createOrder, [order]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.Order>>);

  @override
  _i3.Future<_i5.Result<_i4.Order>> updateOrder(_i4.Order? order) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrder, [order]),
            returnValue: _i3.Future<_i5.Result<_i4.Order>>.value(
              _i6.dummyValue<_i5.Result<_i4.Order>>(
                this,
                Invocation.method(#updateOrder, [order]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.Order>>);

  @override
  _i3.Future<_i5.Result<_i4.Order>> completeOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#completeOrder, [id]),
            returnValue: _i3.Future<_i5.Result<_i4.Order>>.value(
              _i6.dummyValue<_i5.Result<_i4.Order>>(
                this,
                Invocation.method(#completeOrder, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.Order>>);

  @override
  _i3.Future<_i5.Result<_i4.Order>> voidOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#voidOrder, [id]),
            returnValue: _i3.Future<_i5.Result<_i4.Order>>.value(
              _i6.dummyValue<_i5.Result<_i4.Order>>(
                this,
                Invocation.method(#voidOrder, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.Order>>);

  @override
  _i3.Future<_i5.Result<int>> deleteOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOrder, [id]),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i6.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#deleteOrder, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);

  @override
  _i3.Stream<List<_i4.Order>> watchOrdersByStatus(
    _i4.OrderStatus? orderStatus,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchOrdersByStatus, [orderStatus]),
            returnValue: _i3.Stream<List<_i4.Order>>.empty(),
          )
          as _i3.Stream<List<_i4.Order>>);
}

/// A class which mocks [InventoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryRepository extends _i1.Mock
    implements _i7.InventoryRepository {
  MockInventoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<({int productId, int quantity})>> watchAllStocks() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllStocks, []),
            returnValue:
                _i3.Stream<List<({int productId, int quantity})>>.empty(),
          )
          as _i3.Stream<List<({int productId, int quantity})>>);

  @override
  _i3.Stream<
    List<({String name, int productId, int quantity, bool trackStock})>
  >
  watchStockLevels() =>
      (super.noSuchMethod(
            Invocation.method(#watchStockLevels, []),
            returnValue:
                _i3.Stream<
                  List<
                    ({
                      String name,
                      int productId,
                      int quantity,
                      bool trackStock,
                    })
                  >
                >.empty(),
          )
          as _i3.Stream<
            List<({String name, int productId, int quantity, bool trackStock})>
          >);

  @override
  _i3.Stream<({int productId, int quantity})?> watchStockByProductId(
    int? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchStockByProductId, [productId]),
            returnValue: _i3.Stream<({int productId, int quantity})?>.empty(),
          )
          as _i3.Stream<({int productId, int quantity})?>);

  @override
  _i3.Stream<List<({int productId, int quantity})>> watchLowStocks(
    int? threshold,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchLowStocks, [threshold]),
            returnValue:
                _i3.Stream<List<({int productId, int quantity})>>.empty(),
          )
          as _i3.Stream<List<({int productId, int quantity})>>);

  @override
  _i3.Stream<
    List<
      ({
        int id,
        int productId,
        int quantityChange,
        String reason,
        DateTime timestamp,
      })
    >
  >
  watchMovementsByProductId(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#watchMovementsByProductId, [productId]),
            returnValue:
                _i3.Stream<
                  List<
                    ({
                      int id,
                      int productId,
                      int quantityChange,
                      String reason,
                      DateTime timestamp,
                    })
                  >
                >.empty(),
          )
          as _i3.Stream<
            List<
              ({
                int id,
                int productId,
                int quantityChange,
                String reason,
                DateTime timestamp,
              })
            >
          >);

  @override
  _i3.Future<_i5.Result<int>> getStockQuantity(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getStockQuantity, [productId]),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i6.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#getStockQuantity, [productId]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);

  @override
  _i3.Future<_i5.Result<({int productId, int quantity})?>> getStockByProductId(
    int? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getStockByProductId, [productId]),
            returnValue:
                _i3.Future<_i5.Result<({int productId, int quantity})?>>.value(
                  _i6.dummyValue<_i5.Result<({int productId, int quantity})?>>(
                    this,
                    Invocation.method(#getStockByProductId, [productId]),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<({int productId, int quantity})?>>);

  @override
  _i3.Future<_i5.Result<int>> getStocksCount() =>
      (super.noSuchMethod(
            Invocation.method(#getStocksCount, []),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i6.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#getStocksCount, []),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);

  @override
  _i3.Future<
    _i5.Result<
      List<
        ({
          int id,
          int productId,
          int quantityChange,
          String reason,
          DateTime timestamp,
        })
      >
    >
  >
  getMovementHistory({
    int? productId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMovementHistory, [], {
              #productId: productId,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue:
                _i3.Future<
                  _i5.Result<
                    List<
                      ({
                        int id,
                        int productId,
                        int quantityChange,
                        String reason,
                        DateTime timestamp,
                      })
                    >
                  >
                >.value(
                  _i6.dummyValue<
                    _i5.Result<
                      List<
                        ({
                          int id,
                          int productId,
                          int quantityChange,
                          String reason,
                          DateTime timestamp,
                        })
                      >
                    >
                  >(
                    this,
                    Invocation.method(#getMovementHistory, [], {
                      #productId: productId,
                      #startDate: startDate,
                      #endDate: endDate,
                    }),
                  ),
                ),
          )
          as _i3.Future<
            _i5.Result<
              List<
                ({
                  int id,
                  int productId,
                  int quantityChange,
                  String reason,
                  DateTime timestamp,
                })
              >
            >
          >);

  @override
  _i3.Future<_i5.Result<({int productId, int quantity})>> adjustStock({
    required int? productId,
    required int? delta,
    required String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#adjustStock, [], {
              #productId: productId,
              #delta: delta,
              #reason: reason,
            }),
            returnValue:
                _i3.Future<_i5.Result<({int productId, int quantity})>>.value(
                  _i6.dummyValue<_i5.Result<({int productId, int quantity})>>(
                    this,
                    Invocation.method(#adjustStock, [], {
                      #productId: productId,
                      #delta: delta,
                      #reason: reason,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<({int productId, int quantity})>>);

  @override
  _i3.Future<_i5.Result<({int productId, int quantity})>> setStock({
    required int? productId,
    required int? quantity,
    required String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setStock, [], {
              #productId: productId,
              #quantity: quantity,
              #reason: reason,
            }),
            returnValue:
                _i3.Future<_i5.Result<({int productId, int quantity})>>.value(
                  _i6.dummyValue<_i5.Result<({int productId, int quantity})>>(
                    this,
                    Invocation.method(#setStock, [], {
                      #productId: productId,
                      #quantity: quantity,
                      #reason: reason,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<({int productId, int quantity})>>);

  @override
  _i3.Future<_i5.Result<({int productId, int quantity})>> decrementForOrder({
    required int? productId,
    required int? quantity,
    required int? orderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decrementForOrder, [], {
              #productId: productId,
              #quantity: quantity,
              #orderId: orderId,
            }),
            returnValue:
                _i3.Future<_i5.Result<({int productId, int quantity})>>.value(
                  _i6.dummyValue<_i5.Result<({int productId, int quantity})>>(
                    this,
                    Invocation.method(#decrementForOrder, [], {
                      #productId: productId,
                      #quantity: quantity,
                      #orderId: orderId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<({int productId, int quantity})>>);

  @override
  _i3.Future<_i5.Result<({int productId, int quantity})>>
  restoreForVoidedOrder({
    required int? productId,
    required int? quantity,
    required int? orderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#restoreForVoidedOrder, [], {
              #productId: productId,
              #quantity: quantity,
              #orderId: orderId,
            }),
            returnValue:
                _i3.Future<_i5.Result<({int productId, int quantity})>>.value(
                  _i6.dummyValue<_i5.Result<({int productId, int quantity})>>(
                    this,
                    Invocation.method(#restoreForVoidedOrder, [], {
                      #productId: productId,
                      #quantity: quantity,
                      #orderId: orderId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<({int productId, int quantity})>>);
}
