name: feature_pos
description: Point of sale screen feature
publish_to: none
resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.5'

dependencies:
  auto_route: ^11.1.0
  bloc_exports:
    path: ../../packages/bloc
  feature_discounts:
    path: ../discounts
  feature_flags:
    path: ../../packages/feature_flags
  feature_orders:
    path: ../orders
  feature_products:
    path: ../products
  feature_settings:
    path: ../settings
  flutter:
    sdk: flutter
  i18n:
    path: ../../packages/i18n
  printing:
    path: ../../packages/printing
  ui_kit:
    path: ../../packages/ui_kit
  utils:
    path: ../../packages/utils

dev_dependencies:
  flutter_test:
    sdk: flutter
